export const data = [
  {
    _id: '5e45b958990fa4001594183e',
    product: 'HMO',
    payor: 'HN',
    ipa: 'CANOPY HEALTH - HILL PHYSICIANS SAN FRANCISCO',
    _acl: {
      creator: 'kid_By7E3MVHb',
    },
    enableDisable: {
      notifications: 'Enabled',
      myHealthPlan: 'Enabled',
      healthInfo: 'Enabled',
      costEstimator: 'Enabled',
      outOfPocket: 'Enabled',
      doctorsServices: 'Disabled',
      customerSupport: 'Enabled',
      grievances: 'Enabled',
      videoVisits: 'Disabled',
      videoVisitProviders: 'CH_Amwell',
      dsProviders: null,
      dsHospitals: null,
      dsServices: null,
      dsUrgentCare: null,
    },
    grievancesInfo: {
      htmlUrl: 'https://www-{{ENV}}.canopyhealth.com/en/grievances-and-appeals/health-net.html',
      pdfUrl:
        'https://www-{{ENV}}.canopyhealth.com/content/dam/grievance-forms/HealthNet_CA_Grievance_English.pdf',
      staticContentKey: 'grievancesAppeals',
    },
    brandingLogos: {
      LogoPosition1: 'Canopy',
      LogoPosition2: 'HealthNet',
      LogoPosition3: 'Dignity',
      LogoPosition4: '',
    },
    _kmd: {
      lmt: '2020-10-19T21:41:10.403Z',
      ect: '2020-02-13T21:02:16.726Z',
    },
    categoryName: '*',
    groupId: '*',
  },
  {
    _id: '5e45b95838029900165d83cb',
    product: 'HMO',
    payor: 'UHC',
    ipa: 'Meritage 5',
    _acl: {
      creator: '5e51b71d38029900165d9c44',
    },
    enableDisable: {
      notifications: 'Disabled',
      myHealthPlan: 'Disabled',
      healthInfo: 'Enabled',
      costEstimator: 'Enabled',
      outOfPocket: 'DisabledDashboard',
      doctorsServices: 'Enabled',
      customerSupport: 'Enabled',
      grievances: 'Enabled',
      videoVisits: 'Enabled',
      videoVisitProviders: 'UHC-VV',
      genericNavSection1: 'Enabled',
      genericNavSection2: 'Enabled',
    },
    grievancesInfo: {
      htmlUrl:
        'https://www-{{ENV}}.canopyhealth.com/en/grievances-and-appeals/unitedhealthcare.html',
      pdfUrl:
        'https://www-{{ENV}}.canopyhealth.com/content/dam/grievance-forms/UnitedHealthcare_CA_Grievance_English.pdf',
      staticContentKey: 'grievancesAppealsUHC',
    },
    brandingLogos: {
      LogoPosition1: 'Canopy',
      LogoPosition2: '',
      LogoPosition3: 'UHC',
      LogoPosition4: 'Meritage',
    },
    _kmd: {
      lmt: '2020-04-29T15:34:03.746Z',
      ect: '2020-02-28T20:05:34.431Z',
    },
    categoryName: '*',
    groupId: '*',
  },
  {
    _id: '5e45b958088e820015e8560f',
    product: 'HMO',
    payor: 'HN',
    ipa: 'SCCIPA 5',
    _acl: {
      creator: '5e51b71d38029900165d9c44',
    },
    enableDisable: {
      notifications: 'Disabled',
      myHealthPlan: 'Disabled',
      healthInfo: 'Enabled',
      costEstimator: 'Enabled',
      outOfPocket: 'DisabledDashboard',
      doctorsServices: 'Enabled',
      customerSupport: 'Disabled',
      grievances: 'Disabled',
      videoVisits: 'Enabled',
      videoVisitProviders: '',
    },
    grievancesInfo: {
      htmlUrl: 'https://www-{{ENV}}.canopyhealth.com/en/grievances-and-appeals/health-net.html',
      pdfUrl:
        'https://www-{{ENV}}.canopyhealth.com/content/dam/grievance-forms/HealthNet_CA_Grievance_English.pdf',
      staticContentKey: 'grievancesAppeals',
    },
    brandingLogos: {
      LogoPosition1: 'Canopy',
      LogoPosition2: 'HealthNet',
      LogoPosition3: 'SCCIPA',
      LogoPosition4: '',
    },
    _kmd: {
      lmt: '2020-03-05T16:07:44.274Z',
      ect: '2020-02-28T20:05:34.431Z',
    },
    categoryName: '*',
    groupId: '*',
  },
  {
    _id: '5e45b958990fa4001594183d',
    product: 'HMO',
    payor: 'UHC',
    ipa: 'Hill 2',
    _acl: {
      creator: '5e51b71d38029900165d9c44',
    },
    _kmd: {
      lmt: '2020-02-28T20:05:34.431Z',
      ect: '2020-02-28T20:05:34.431Z',
    },
    enableDisable: {
      notifications: 'Enabled',
      myHealthPlan: 'Enabled',
      healthInfo: 'Enabled',
      costEstimator: 'Enabled',
      outOfPocket: 'Enabled',
      doctorsServices: 'Disabled',
      customerSupport: 'Enabled',
      grievances: 'Enabled',
      videoVisits: 'Disabled',
      videoVisitProviders: 'CH_Amwell',
    },
    grievancesInfo: {
      htmlUrl:
        'https://www-{{ENV}}.canopyhealth.com/en/grievances-and-appeals/unitedhealthcare.html',
      pdfUrl:
        'https://www-{{ENV}}.canopyhealth.com/content/dam/grievance-forms/UnitedHealthcare_CA_Grievance_English.pdf',
      staticContentKey: 'grievancesAppealsUHC',
    },
    brandingLogos: {
      LogoPosition1: 'Canopy',
      LogoPosition2: null,
      LogoPosition3: 'UHC',
      LogoPosition4: 'Hill',
    },
    categoryName: '*',
    groupId: '*',
  },
  {
    _id: '5e45b958088e820015e8560e',
    product: 'HMO',
    payor: 'UHC',
    ipa: 'SCCIPA 8',
    _acl: {
      creator: '5e51b71d38029900165d9c44',
    },
    enableDisable: {
      notifications: 'Disabled',
      myHealthPlan: 'Disabled',
      healthInfo: 'Disabled',
      costEstimator: 'Disabled',
      outOfPocket: 'Disabled',
      doctorsServices: 'Enabled',
      customerSupport: 'Enabled',
      grievances: 'Enabled',
      videoVisits: 'Disabled',
      videoVisitProviders: '',
      genericNavSection1: null,
      genericNavSection2: null,
    },
    grievancesInfo: {
      htmlUrl:
        'https://www-{{ENV}}.canopyhealth.com/en/grievances-and-appeals/unitedhealthcare.html',
      pdfUrl:
        'https://www-{{ENV}}.canopyhealth.com/content/dam/grievance-forms/UnitedHealthcare_CA_Grievance_English.pdf',
      staticContentKey: 'grievancesAppealsUHC',
    },
    brandingLogos: {
      LogoPosition1: 'Canopy',
      LogoPosition2: 'UHC',
      LogoPosition3: 'SCCIPA',
      LogoPosition4: '',
    },
    _kmd: {
      lmt: '2020-05-12T19:25:04.732Z',
      ect: '2020-02-28T20:05:34.431Z',
    },
    categoryName: '*',
    groupId: '*',
  },
  {
    _id: '5e45b958088e820015e85611',
    product: 'HMO',
    payor: 'HN',
    ipa: 'Dignity 4',
    _acl: {
      creator: '5e51b71d38029900165d9c44',
    },
    _kmd: {
      lmt: '2020-02-28T20:05:34.431Z',
      ect: '2020-02-28T20:05:34.431Z',
    },
    enableDisable: {
      notifications: 'Enabled',
      myHealthPlan: 'Enabled',
      healthInfo: 'Enabled',
      costEstimator: 'Disabled',
      outOfPocket: 'Enabled',
      doctorsServices: 'Enabled',
      customerSupport: 'Enabled',
      grievances: 'Enabled',
      videoVisits: 'Enabled',
      videoVisitProviders: 'CH_Amwell',
    },
    grievancesInfo: {
      htmlUrl: 'https://www-{{ENV}}.canopyhealth.com/en/grievances-and-appeals/health-net.html',
      pdfUrl:
        'https://www-{{ENV}}.canopyhealth.com/content/dam/grievance-forms/HealthNet_CA_Grievance_English.pdf',
      staticContentKey: 'grievancesAppeals',
    },
    brandingLogos: {
      LogoPosition1: 'Canopy',
      LogoPosition2: 'Dignity',
      LogoPosition3: null,
      LogoPosition4: null,
    },
    categoryName: '*',
    groupId: '*',
  },
  {
    _id: '5e45b95838029900165d83cc',
    product: 'HMO',
    payor: 'HN',
    ipa: 'Hill 5',
    _acl: {
      creator: '5e51b71d38029900165d9c44',
    },
    enableDisable: {
      notifications: 'Disabled',
      myHealthPlan: 'Disabled',
      healthInfo: 'Enabled',
      costEstimator: 'Disabled',
      outOfPocket: 'DisabledDashboard',
      doctorsServices: 'Enabled',
      customerSupport: 'Disabled',
      grievances: 'Disabled',
      videoVisits: 'Enabled',
      videoVisitProviders: '',
      dsProviders: 'Enabled',
      dsHospitals: 'Enabled',
      dsServices: 'Enabled',
      dsUrgentCare: 'Enabled',
    },
    grievancesInfo: {
      htmlUrl: 'https://www-{{ENV}}.canopyhealth.com/en/grievances-and-appeals/health-net.html',
      pdfUrl:
        'https://www-{{ENV}}.canopyhealth.com/content/dam/grievance-forms/HealthNet_CA_Grievance_English.pdf',
      staticContentKey: 'grievancesAppeals',
    },
    brandingLogos: {
      LogoPosition1: 'Canopy',
      LogoPosition2: 'HealthNet',
      LogoPosition3: 'Hill',
      LogoPosition4: '',
    },
    _kmd: {
      lmt: '2020-07-30T15:50:08.161Z',
      ect: '2020-02-28T20:05:34.431Z',
    },
    categoryName: '*',
    groupId: '*',
  },
  {
    _id: '5e45b958990fa4001594183f',
    product: 'HMO',
    payor: 'UHC',
    ipa: 'JMH 4',
    _acl: {
      creator: '5e51b71d38029900165d9c44',
    },
    enableDisable: {
      notifications: 'Enabled',
      myHealthPlan: 'Enabled',
      healthInfo: 'Enabled',
      costEstimator: 'Disabled',
      outOfPocket: 'Enabled',
      doctorsServices: 'Enabled',
      customerSupport: 'Enabled',
      grievances: 'Enabled',
      videoVisits: 'Enabled',
      videoVisitProviders: 'CH_Amwell, JMH_VV, UHC-VV',
      genericNavSection1: 'Enabled',
      genericNavSection2: 'Enabled',
    },
    grievancesInfo: {
      htmlUrl:
        'https://www-{{ENV}}.canopyhealth.com/en/grievances-and-appeals/unitedhealthcare.html',
      pdfUrl:
        'https://www-{{ENV}}.canopyhealth.com/content/dam/grievance-forms/UnitedHealthcare_CA_Grievance_English.pdf',
      staticContentKey: 'grievancesAppealsUHC',
    },
    brandingLogos: {
      LogoPosition1: 'Canopy',
      LogoPosition2: 'JMH',
      LogoPosition3: '',
      LogoPosition4: '',
    },
    _kmd: {
      lmt: '2020-04-01T14:04:22.091Z',
      ect: '2020-02-28T20:05:34.431Z',
    },
    categoryName: '*',
    groupId: '*',
  },
];
